// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArvFHcf_9MAONyzLQx4iuDd4vQQm4k6jE',
    appId: '1:889258359516:web:d1251b7f6ac95c9c2b9219',
    messagingSenderId: '889258359516',
    projectId: 'uts-abel',
    authDomain: 'uts-abel.firebaseapp.com',
    databaseURL: 'https://uts-abel-default-rtdb.firebaseio.com',
    storageBucket: 'uts-abel.appspot.com',
    measurementId: 'G-GE5TW3V44D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbUOYBeRcc14PRwv4Ddf3h4VAxSpvu-t4',
    appId: '1:889258359516:android:ee77deb119968c4b2b9219',
    messagingSenderId: '889258359516',
    projectId: 'uts-abel',
    databaseURL: 'https://uts-abel-default-rtdb.firebaseio.com',
    storageBucket: 'uts-abel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxE_ggHYsttVFL5zlDouzOQ7di6sCsIIE',
    appId: '1:889258359516:ios:fdd6a219bd6543692b9219',
    messagingSenderId: '889258359516',
    projectId: 'uts-abel',
    databaseURL: 'https://uts-abel-default-rtdb.firebaseio.com',
    storageBucket: 'uts-abel.appspot.com',
    iosBundleId: 'com.example.utsAbeldelando2125240024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxE_ggHYsttVFL5zlDouzOQ7di6sCsIIE',
    appId: '1:889258359516:ios:fdd6a219bd6543692b9219',
    messagingSenderId: '889258359516',
    projectId: 'uts-abel',
    databaseURL: 'https://uts-abel-default-rtdb.firebaseio.com',
    storageBucket: 'uts-abel.appspot.com',
    iosBundleId: 'com.example.utsAbeldelando2125240024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArvFHcf_9MAONyzLQx4iuDd4vQQm4k6jE',
    appId: '1:889258359516:web:0e738588b5e836ed2b9219',
    messagingSenderId: '889258359516',
    projectId: 'uts-abel',
    authDomain: 'uts-abel.firebaseapp.com',
    databaseURL: 'https://uts-abel-default-rtdb.firebaseio.com',
    storageBucket: 'uts-abel.appspot.com',
    measurementId: 'G-G6GPHN3LLB',
  );
}
